### ISSUE TITLE
Support Apollo Server

### ISSUE THREAD

**Issue by lorensr** [ef-eng/graphql-query-rewriter#2]
I see in the README that this is planned—just opening this issue to track it ☺️

**Comment by chanind** [comment]
Thanks for the push on this! Hopefully it should happen in the next week or so

**Comment by chanind** [comment]
Actually, it looks like ApolloServer already works with `express-graphql-query-rewriter`. using the middleware pattern described in the [apollo docs](https://www.apollographql.com/docs/apollo-server/migration-two-dot/#middleware). For example:

```js
const { ApolloServer, gql } = require("apollo-server-express");
const express = require("express");
const { graphqlRewriterMiddleware } = require("express-graphql-query-rewriter");

const server = new ApolloServer({ typeDefs, resolvers });

const app = express();
const graphqlPath = "/graphql";
app.use(
  graphqlPath,
  graphqlRewriterMiddleware({
    rewriters: [
      // rewriters here as usual
    ]
  })
);
server.applyMiddleware({ app, graphqlPath, bodyParserConfig: false });

app.listen({ port: 4000 }, () => {
  console.log(`🚀 Server ready at http://localhost:4000${server.graphqlPath}`);
});
```

It seems like the tricky part is passing `bodyParserConfig: false`, since `express-graphql-query-rewriter` already parses the body of the request in order to do the rewriting.

**Comment by chanind** [comment]
I updated the README with instructions for apollo-server, so closing this issue for now
